/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../../src/angular2-tinymce.component';
import * as i2 from '@angular/forms';
const styles_TinymceComponent:any[] = ([] as any[]);
export const RenderType_TinymceComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_TinymceComponent,data:{}});
export function View_TinymceComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),0,'div',([] as any[]),
      [[8,'id',0]],(null as any),(null as any),(null as any),(null as any)))],(null as any),
      (_ck,_v) => {
        var _co:i1.TinymceComponent = _v.component;
        const currVal_0:any = i0.ɵinlineInterpolate(1,'',_co.elementId,'');
        _ck(_v,0,0,currVal_0);
      });
}
export function View_TinymceComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),2,'app-tinymce',
      ([] as any[]),(null as any),(null as any),(null as any),View_TinymceComponent_0,
      RenderType_TinymceComponent)),i0.ɵprd(5120,(null as any),i2.NG_VALUE_ACCESSOR,
      (p0_0:any) => {
        return [p0_0];
      },[i1.TinymceComponent]),i0.ɵdid(4374528,(null as any),0,i1.TinymceComponent,
      [i0.NgZone,'TINYMCE_CONFIG'],(null as any),(null as any))],(null as any),(null as any));
}
export const TinymceComponentNgFactory:i0.ComponentFactory<i1.TinymceComponent> = i0.ɵccf('app-tinymce',
    i1.TinymceComponent,View_TinymceComponent_Host_0,{config:'config'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3Npam1lbnZvcy9Eb2N1bWVudHMvUHJvamVjdHMvYW5ndWxhcjItdGlueW1jZS9zcmMvYW5ndWxhcjItdGlueW1jZS5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvc2lqbWVudm9zL0RvY3VtZW50cy9Qcm9qZWN0cy9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL3Npam1lbnZvcy9Eb2N1bWVudHMvUHJvamVjdHMvYW5ndWxhcjItdGlueW1jZS9zcmMvYW5ndWxhcjItdGlueW1jZS5jb21wb25lbnQudHMuVGlueW1jZUNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvc2lqbWVudm9zL0RvY3VtZW50cy9Qcm9qZWN0cy9hbmd1bGFyMi10aW55bWNlL3NyYy9hbmd1bGFyMi10aW55bWNlLmNvbXBvbmVudC50cy5UaW55bWNlQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGRpdiBpZD1cInt7ZWxlbWVudElkfX1cIj48L2Rpdj4iLCI8YXBwLXRpbnltY2U+PC9hcHAtdGlueW1jZT4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7b0JDQUE7TUFBQTs7O1FBQUs7UUFBTCxXQUFLLFNBQUw7Ozs7b0JDQUE7TUFBQTtpQ0FBQTtNQUFBO1FBQUE7TUFBQSxnQ0FBQTtNQUFBOzs7In0=
